### ISSUE TITLE
depedit.ini required file ?

### ISSUE THREAD

**Issue by ftyers** [amir-zeldes/xrenner#54]
In the documentation it says that only five files are necessary, but if I try and set up a new model with only those five files, I get:

```
$ python3 xrenner.py -o conll -m rus ~/source/ftyers.github.io/028-komp-ling/classes/pushkin.conllu 
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "xrenner.py", line 66, in xrenner_worker
    xrenner = Xrenner(model, override)
  File "/home/fran/source/xrenner/xrenner/modules/xrenner_xrenner.py", line 33, in __init__
    depedit_config = self.lex.model_files["depedit.ini"]
KeyError: 'depedit.ini'
```

If I do `touch depedit.ini` in `models/rus`, then it works.

**Comment by amir-zeldes** [comment]
Hm, that's right, there's no real reason it needs depedit. I should just make that optional too once I have a chance. Sorry about the confusion!
